ACTIVE_PROFILE: dev

PRIVATE_KEY: 'private.key'
PUBLIC_KEY: 'public.key'

POSTGRES_USERNAME: 'deceptiveb'
POSTGRES_DATABASE: 'stock'
POSTGRES_HOST: 'localhost'
POSTGRES_PORT: 5432
POSTGRES_PASSWORD: 'deceptiveb'

SERVER_PORT: 8080
UI_APP_URL: http://localhost:5173